[features]
seeds = true
skip-lint = false
[programs.localnet]
team_dao = "DX9sn7m7pn3zQJP5B5oD5YQVQWxen9CX77u8rEqMFC41"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/fuujack/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
teamdao = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/TeamDao.ts"
tournament = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/Tournament.ts"

[test]
startup_wait = 15000

